yum update -y ; sleep 3 ;
yum install httpd -y ; sleep 3 ;
systemctl start httpd ; sleep 3 ;
systemctl enable httpd ; sleep 3 ;
yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y ; sleep 3 ;
yum install https://rpms.remirepo.net/enterprise/remi-release-7.rpm -y ; sleep 3 ;
yum install yum-utils -y ; sleep 3 ;
yum-config-manager --enable remi-php74 ; sleep 3 ;
yum update -y ; sleep 3 ;
yum install php -y ; sleep 3 ;
yum install php-dom -y ; sleep 3 ;
yum install php-gd -y ; sleep 3 ;
yum install php-libxml -y ; sleep 3 ;
yum install php-mbstring -y ; sleep 3 ;
yum install php-posix -y ; sleep 3 ;
yum install php-zip -y ; sleep 3 ;
yum install php-pdo_mysql -y ; sleep 3 ;
yum install php-intl -y ; sleep 3 ;
yum install php-ldap -y ; sleep 3 ;
yum install php-smbclient -y ; sleep 3 ;
yum install php-imap -y ; sleep 3 ;
yum install php-bcmath -y ; sleep 3 ;
yum install php-gmp -y ; sleep 3 ;
yum install php-apcu -y ; sleep 3 ;
yum install php-memcached -y ; sleep 3 ;
yum install php-redis -y ; sleep 3 ;
yum install php-imagick -y ; sleep 3 ;
firewall-cmd --permanent --add-service=http ; sleep 3 ;
firewall-cmd --permanent --add-service=https ; sleep 3 ;
firewall-cmd --reload ; sleep 3 ;
yum install mariadb-server mariadb -y ; sleep 3 ;
systemctl start mariadb ; sleep 3 ;
systemctl enable mariadb ; sleep 3 ;
mysql_secure_installation ; sleep 3 ;
yum install git -y ; sleep 3 ;
cd /var/www/ ; sleep 3 ;
git clone https://github.com/aajay932/deecloud.git ; sleep 3 ;
chown -R apache:apache /var/www/deecloud/ ; sleep 3 ;
systemctl restart httpd ; sleep 3 ;
setenforce 0
